# Later loaded definition wins for existing fields.
# So higher priority import should be written in ${os}.toml
# You can find major themes in https://github.com/alacritty/alacritty-theme
import = [
  "~/.config/alacritty/themes/iceberg-dark.toml",
]

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Beam"

[font]
size = 12

[font.normal]
family = "PlemolJP Console NF"
style = "Regular"

[font.bold]
family = "PlemolJP Console NF"
style = "Italic"

[font.italic]
family = "PlemolJP Console NF"
style = "Bold"

[font.bold_italic]
family = "PlemolJP Console NF"
style = "Bold Italic"

[window]
opacity = 0.85

dimensions.columns = 180
dimensions.lines = 50

position.x = 10
position.y = 10
