# You can find major themes in https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/iceberg-dark.toml"]

[font.normal]
family = "PlemolJP Console NF"

[window]
opacity = 0.85
