# https://wiki.archlinux.org/title/Alacritty

[window]
# https://github.com/alacritty/alacritty/issues/93
option_as_alt = "Both"

# - macOS has newer zsh by default
# - bash is installed, but the version is too old 3.x by default
# [terminal.shell]
# So no config will work
