[terminal.shell]
program = "wsl"
args = [
  "--cd",
  "~",
]
# windows default is in my experimental state. Note pwsh pattern as follows
#
# program = "pwsh" # Not "powershell", that is default, but too old
# args = [
#   "-WorkingDirectory",
#   "~/",
# ]

[[keyboard.bindings]]
action = "Paste"
# Trade-off, I prefer windows conversation. But keep in mind, ctrl + v is preserved in bash https://news.mynavi.jp/techplus/article/techp5555/
mods = "Control"
key = "V"
