#!/usr/bin/env bash

set -euxo pipefail

shopt -s globstar

dprint check
shfmt --diff ./**/*.sh ./**/*.bash scripts/*.bash .config/.bashrc
shellcheck ./**/*.sh ./**/*.bash scripts/*.bash .config/.bashrc
gitleaks detect
