#!/usr/bin/env ruby
# frozen_string_literal: true

# Imported from https://github.com/kachick/irb-power_assert/blob/98ad68b4c391bb30adee1ba119cb6c6ed5bd0bfc/examples/.irbrc

require 'irb/power_assert'

IRB::Context.prepend(Module.new{
  kwargs = Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.7.0') ? ', **' : ''
  line = __LINE__; eval %q{
    def evaluate(line, *__ARGS__)
      case line
      when /\Apa /
        line.replace("pa #{line.sub(/\Apa +/, '').strip.dump}\n")
      end
      super
    end
  }.sub(/__ARGS__/, kwargs), nil, __FILE__, line
})
