[config]
skip_core_tasks = true

[tasks.default]
alias = "help"

[tasks.help]
script = [
  'makers --list-all-steps',
]

[tasks.setup]
script = [
  "git config --local core.hooksPath .githooks",
]

[tasks.update]
script = [
  "dprint config update --yes",
]

[tasks.lint]
command = './scripts/lint.bash'

[tasks.fmt]
command = './scripts/fmt.bash'

[tasks.check]
alias = "lint"

[tasks.deps]
command = './scripts/print-deps.bash'
