[config]
skip_core_tasks = true

[tasks.default]
alias = "help"

[tasks.help]
script = [
  'makers --list-all-steps',
]

[tasks.setup]
script = [
  "git config --local core.hooksPath .githooks",
]

[tasks.update]
script = [
  "dprint config update --yes",
]

[tasks.format-check]
script = [
  "dprint check",
]

[tasks.format-apply]
script = [
  "dprint fmt",
]

[tasks.fmt]
alias = "format-apply"

[tasks.typos-check]
script = [
  "typos",
]

[tasks.prevent-secret]
script = [
  "gitleaks detect",
]

[tasks.check]
run_task = { name = ["typos-check", "format-check", "prevent-secret"] }

[tasks.deps]
script = [
  "makers --version",
  "nix --version",
  "dprint --version",
  "shellcheck --version",
  "shfmt --version",
  # Returns NON 0, why...? :<
  # "nixpkgs-fmt --version",
  "gitleaks version",
  "fd --version",
  "typos --version",
]
