[config]
skip_core_tasks = true

[tasks.default]
alias = "help"

[tasks.help]
script = [
  'makers --list-all-steps',
]

[tasks.setup]
dependencies = ['build']
script = [
  "git config --local core.hooksPath .githooks",
]

[tasks.update]
script = [
  "nix run github:kachick/nixpkgs-url -- bump",
  "dprint config update --yes",
]

[tasks.lint]
command = 'dist/lint'

[tasks.fmt]
command = 'dist/fmt'

[tasks.check]
alias = "lint"

[tasks.deps]
command = 'dist/deps'

[tasks.prepare-build]
command = 'mkdir'
args = ['-p', 'dist']

[tasks.build]
dependencies = ['prepare-build']
command = 'go'
args = [
  'build',
  '-v',
  '-o',
  'dist',
  './...',
]

[tasks.test-race]
dependencies = ['prepare-build']
command = 'go'
args = [
  'build',
  '-v',
  '-race',
  '-o',
  'dist',
  './...',
]

[tasks.apply]
command = 'home-manager'
args = [
  'switch',
  '-f',
  './home/.config/home-manager/home.nix',
]

[tasks.ci-home-apply]
command = 'home-manager'
args = [
  'switch',
  '-f',
  './home/.config/home-manager/github-actions.nix',
]

[tasks.enable_login_shells]
command = 'sudo'
args = [
  '-E',
  'dist/enable_nix_login_shells',
]

[tasks.ci]
dependencies = [
  'default',
  'setup',
  'deps',
  'build',
  'test-race',
  'fmt',
  'check',
]
