[config]
skip_core_tasks = true

[tasks.default]
alias = "help"

[tasks.help]
script = [
  'makers --list-all-steps',
]

[tasks.setup]
dependencies = ['build']
script = [
  "git config --local core.hooksPath .githooks",
  "git config --local core.whitespace cr-at-eol",
]

[tasks.update]
script = [
  "nix flake update --commit-lock-file",
]

[tasks.lint]
dependencies = ['build']
command = 'dist/lint'

[tasks.lint-all]
dependencies = ['build']
command = 'dist/lint'
args = ['-all']

[tasks.fmt]
dependencies = ['build']
command = 'dist/fmt'

[tasks.check]
dependencies = [
  'build',
  'test',
  'lint-all',
  'build-go-race-as-the-race-test',
]

[tasks.deps]
dependencies = ['build']
command = 'dist/deps'

[tasks.prepare-build]
command = 'mkdir'
args = ['-p', 'dist/race']

[tasks.build]
dependencies = ['prepare-build']
command = 'go'
args = [
  'build',
  '-v',
  '-o',
  'dist',
  './...',
]

[tasks.build-go-race-as-the-race-test]
dependencies = ['prepare-build']
command = 'go'
args = [
  'build',
  '-v',
  '-race',
  '-o',
  'dist/race',
  './...',
]

[tasks.test-go]
command = 'go'
args = [
  'test',
  './...',
]

[tasks.test]
dependencies = [
  'test-go',
]
command = 'nix'
args = [
  'run',
  '.#home-manager',
  '--',
  'switch',
  '-n', # dry-run
  '-b',
  'backup',
  '--flake',
  '.#kachick',
]

[tasks.apply]
command = 'nix'
args = [
  'run',
  '.#home-manager',
  '--',
  'switch',
  '-b',
  'backup',
  '--flake',
  '.#kachick',
]

[tasks.ci-dev]
dependencies = [
  'default',
  'setup',
  'deps',
  'build',
  # 'test', # Needs home-manager, so needless in Nix-CI
  'lint-all',
  'test-go',
  'build-go-race-as-the-race-test',
  'fmt',
]

[tasks.build-container]
command = './containers/build.bash'

[tasks.sandbox]
command = './containers/sandbox.bash'

[tasks.sandbox-cr]
command = './containers/sandbox-with-ghcr.bash'
args = [
  'latest',
]
