[config]
skip_core_tasks = true

[tasks.default]
alias = "help"

[tasks.help]
script = [
  'makers --list-all-steps',
]

[tasks.setup]
dependencies = ['build']
script = [
  "git config --local core.hooksPath .githooks",
  "git config --local core.whitespace cr-at-eol",
]

[tasks.update]
script = [
  "nix flake update --commit-lock-file",
]

[tasks.lint]
dependencies = ['build']
command = 'dist/lint'

[tasks.fmt]
dependencies = ['build']
command = 'dist/fmt'

[tasks.check]
dependencies = [
  'build',
  'test',
  'lint',
  'test-go-race',
]

[tasks.deps]
dependencies = ['build']
command = 'dist/deps'

[tasks.prepare-build]
command = 'mkdir'
args = ['-p', 'dist/race']

[tasks.build]
dependencies = ['prepare-build']
command = 'go'
args = [
  'build',
  '-v',
  '-o',
  'dist',
  './...',
]

[tasks.test-go-race]
dependencies = ['prepare-build']
command = 'go'
args = [
  'build',
  '-v',
  '-race',
  '-o',
  'dist/race',
  './...',
]

[tasks.test]
command = 'nix'
args = [
  'run',
  '.#home-manager',
  '--',
  'switch',
  '-n', # dry-run
  '-b',
  'backup',
  '--flake',
  '.#kachick',
]

[tasks.apply]
command = 'nix'
args = [
  'run',
  '.#home-manager',
  '--',
  'switch',
  '-b',
  'backup',
  '--flake',
  '.#kachick',
]

[tasks.enable_login_shells]
dependencies = ['build']
command = 'sudo'
args = [
  '-E',
  'dist/enable_nix_login_shells',
]

[tasks.ci-dev]
dependencies = [
  'default',
  'setup',
  'deps',
  'build',
  # 'test', # Needs home-manager, so needless in Nix-CI
  'lint',
  'test-go-race',
  'fmt',
]
