# One CLI to format the code tree - https://github.com/numtide/treefmt

[global]
# "/*" means recursive
excludes = [
  ".git/*",
  ".direnv/*",
  "dist/*",
  "result/*",
  "dependencies/*",
  "*.lock",
]

[formatter.dprint]
command = "dprint"
options = ["fmt"]
includes = [
  "*.json",
  "*.jsonc",
  "*.toml",
  "*.md",
  "*.yaml",
  "*.yml",
  "*.kdl",
]

[formatter.nixfmt-rfc-style]
command = "nixfmt"
includes = ["*.nix"]

[formatter.go]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.shfmt]
command = "shfmt"
options = [
  "--language-dialect",
  # shfmt is not supporting zsh even through specified "auto"
  # https://github.com/mvdan/sh/issues/120
  "bash",
  "--write",
]
includes = ["*.sh", "*.bash", "*.envrc"]
