title = "Custom Betterleaks configuration"

# You have basically two options for your custom configuration:
#
# 1. define your own configuration, default rules do not apply
#
#    use e.g., the default configuration as starting point:
#    https://github.com/betterleaks/betterleaks/blob/main/betterleaks.toml
#
# 2. extend a configuration, the rules are overwritten or extended
#
#    When you extend a configuration the extended rules take precedence over the
#    default rules. I.e., if there are duplicate rules in both the extended
#    configuration and the default configuration the extended rules or
#    attributes of them will override the default rules.
#    Another thing to know with extending configurations is you can chain
#    together multiple configuration files to a depth of 2. Allowlist arrays are
#    appended and can contain duplicates.

# useDefault and path can NOT be used at the same time. Choose one.
[extend]
# useDefault will extend the default betterleaks config built in to the binary
# the latest version is located at:
# https://github.com/betterleaks/betterleaks/blob/main/betterleaks.toml
useDefault = true

# 1. Initially imported from https://github.com/gitleaks/gitleaks/pull/1808
# 2. Keeping this because betterleaks still does not support many tailscale keys except API: https://github.com/betterleaks/betterleaks/commit/f64b922294260c390e4d20442c239b52275247cb
[[rules]]
id = "tailscale-key"
description = "Detected a Tailscale non-API key, potentially allowing unauthorized access to your Tailscale network and connected devices."
regex = '''\btskey-(auth|client|scim|webhook)-[0-9A-Za-z_]+-[0-9A-Za-z_]+\b'''
keywords = [
  "tskey-auth",
  "tskey-client",
  "tskey-scim",
  "tskey-webhook",
]
