title = "Custom Gitleaks configuration"

# You have basically two options for your custom configuration:
#
# 1. define your own configuration, default rules do not apply
#
#    use e.g., the default configuration as starting point:
#    https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
#
# 2. extend a configuration, the rules are overwritten or extended
#
#    When you extend a configuration the extended rules take precedence over the
#    default rules. I.e., if there are duplicate rules in both the extended
#    configuration and the default configuration the extended rules or
#    attributes of them will override the default rules.
#    Another thing to know with extending configurations is you can chain
#    together multiple configuration files to a depth of 2. Allowlist arrays are
#    appended and can contain duplicates.

# useDefault and path can NOT be used at the same time. Choose one.
[extend]
# useDefault will extend the default gitleaks config built in to the binary
# the latest version is located at:
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

# Remove after https://github.com/gitleaks/gitleaks/pull/1808 is available
[[rules]]
id = "tailscale-key"
description = "Detected a Tailscale key, potentially allowing unauthorized access to your Tailscale network and connected devices."
regex = '''\btskey-(api|auth|client|scim|webhook)-[0-9A-Za-z_]+-[0-9A-Za-z_]+\b'''
keywords = [
  "tskey-api",
  "tskey-auth",
  "tskey-client",
  "tskey-scim",
  "tskey-webhook",
]
