# https://github.com/kachick/containers
ARG BASE_IMAGE=ghcr.io/kachick/ubuntu-26.04-nix-systemd:latest@sha256:8c961752e4bcf46087f21e5a032929af7c7088088a21dfb0c511d8c0cc914e27
FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.source=https://github.com/kachick/dotfiles
LABEL org.opencontainers.image.description="Example by kachick/dotfiles"
LABEL org.opencontainers.image.licenses=MIT

USER user
# Docker/Podman doesn't set $USER in the USER instruction, which results in home-manager activation failure
# https://stackoverflow.com/questions/54411218/docker-why-isnt-user-environment-variable-set
ENV USER=user

RUN mkdir -p ~/.local/state/nix/profiles

# Don't use /tmp, it removes in first run
COPY ./ /provisioner/dotfiles/
COPY ./containers/needs_systemd.bash /provisioner/needs_systemd.bash

# Should back to original of kachick/ubuntu-nix-systemd, we need to run systemd first
USER root
CMD ["/usr/lib/systemd/systemd", "--system"]
