# https://github.com/kachick/containers
FROM ghcr.io/kachick/ubuntu-nix-systemd:20240308-103859-utc

LABEL org.opencontainers.image.source=https://github.com/kachick/dotfiles
LABEL org.opencontainers.image.description="Example by kachick/dotfiles"
LABEL org.opencontainers.image.licenses=MIT

USER user
# Docker/Podman doesn't set $USER in USER instruction, and it makes failure in home-manager activation
# https://stackoverflow.com/questions/54411218/docker-why-isnt-user-environment-variable-set
ENV USER=user

RUN mkdir -p ~/.local/state/nix/profiles

# Don't use /tmp, it removes in first run
COPY ./ /provisioner/dotfiles/
COPY ./containers/needs_systemd.bash /provisioner/needs_systemd.bash

# Should back to original of kachick/ubuntu-nix-systemd, we need to run systemd first
USER root
CMD [ "/bin/systemd", "--system" ]
