# https://github.com/kachick/containers
# You can get the digest by using:
# skopeo inspect docker://ghcr.io/kachick/ubuntu-26.04-nix-systemd:latest | jq -r '.Digest'
FROM ghcr.io/kachick/ubuntu-26.04-nix-systemd:latest@sha256:99230df35e5186272c324dfe9d1e5cfe0db5786dc46f37503bd6e1ba81950630

LABEL org.opencontainers.image.source=https://github.com/kachick/dotfiles
LABEL org.opencontainers.image.description="Example by kachick/dotfiles"
LABEL org.opencontainers.image.licenses=MIT

USER user
# Docker/Podman doesn't set $USER in the USER instruction, which results in home-manager activation failure
# https://stackoverflow.com/questions/54411218/docker-why-isnt-user-environment-variable-set
ENV USER=user

RUN mkdir -p ~/.local/state/nix/profiles

# Don't use /tmp, it removes in first run
COPY ./ /provisioner/dotfiles/
COPY ./containers/needs_systemd.bash /provisioner/needs_systemd.bash

# Should back to original of kachick/ubuntu-nix-systemd, we need to run systemd first
USER root
CMD ["/usr/lib/systemd/systemd", "--system"]
