"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$crystal\
$elm\
$haskell\
$rust\
$golang\
$ruby\
$python\
$deno\
$nodejs\
$os\
$container\
$direnv\
$nix_shell\
$shell\
$jobs\
$time\
$cmd_duration\
$status\
$line_break\
$character"""

# https://www.reddit.com/r/NixOS/comments/17eb1ym/comment/k62nxo4/?utm_source=reddit&utm_medium=web2x&context=3
[shlvl]
disabled = false

[directory]
style = "blue"

[direnv]
disabled = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[status]
disabled = false
# Displays as a part of character module
style = "bold red"
format = "[$status]($style)"

[git_commit]
only_detached = false

[git_branch]
format = "[$branch]($style)"
# Changed from https://github.com/starship/starship/pull/3066/files
# https://github.com/sindresorhus/pure/blob/47c0c881f0e7cfdb5eaccd335f52ad17b897c060/pure.zsh#L822
style = "242"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[shell]
disabled = false
bash_indicator = 'bash'

[container]
disabled = false

[os]
disabled = false
