modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
      Alt_L:
        held: Alt_L
        alone: Muhenkan
        alone_timeout_millis: 500 # Optional
      Alt_R: Henkan

keymap:
  - name: Gnome lancher
    remap:
      Alt-Space: LEFTMETA
