# This template inherits from the official Docker template and adds Nix.
# See: https://lima-vm.io/docs/templates/

base:
  - template:docker

user:
  name: 'user'

provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eux -o pipefail

      if ! command -v nix >/dev/null 2>&1; then
          # https://github.com/DeterminateSystems/nix-installer
          curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux \
            --extra-conf "sandbox = false" \
            --init none \
            --no-confirm
      fi

      # Force Nix profile loading for non-interactive shells in Ubuntu.
      if ! grep -q "nix-daemon.sh" /etc/bash.bashrc; then
        sed -i '1i if [ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh; fi' /etc/bash.bashrc
      fi
