# 🟢 Builtin default: [] (Mount nothing)
mounts:
  # TODO: Disable default mounting host home to keep secure even if it is not writable
  # - location: '~' # Just comment out still respects template default. And setting mountPoint as false handles the false as string...
  - location: '~/repos' # See git.nix in this repo
    # Avoid hardcoding '{{.Home}}/repos' to ensure 'limactl shell' can
    # synchronize the working directory by matching the host's absolute path.
    # Also, consider and test compatibility with ghq and wrapped scripts (e.g., cdrepo).
    # mountPoint: '{{.Home}}/repos'
    writable: true # For developing purpose, writable should be reasonable. And my system does not directly include these files

# https://github.com/lima-vm/lima/issues/1015#issuecomment-4092839880
user:
  name: user # Adjust with home-manager. See also home-manager/ephemeral.nix
