name: 'Setup Nix and Cachix'
description: 'Installs Nix and configures Cachix for caching'
inputs:
  cachix-auth-token:
    description: 'Authentication token for Cachix'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      # "DeterminateSystems/nix-installer-action" does not run on x86_64-darwin: https://github.com/DeterminateSystems/nix-src/issues/224
      uses: NixOS/nix-installer-action@main # There are no tagged releases
      with:
        extra-conf: |
          sandbox = true
          accept-flake-config = true
    - name: Cache Nix Evaluation and Tarballs
      uses: actions/cache@v5
      with:
        path: ~/.cache/nix
        key: nix-eval-and-tarball-${{ runner.os }}-${{ hashFiles('flake.lock', '**/*.nix') }}
        restore-keys: |
          nix-eval-and-tarball-${{ runner.os }}-${{ hashFiles('flake.lock') }}-
          nix-eval-and-tarball-${{ runner.os }}-
    - name: Configure Cachix
      uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
      with:
        name: kachick-dotfiles
        authToken: ${{ inputs.cachix-auth-token }}
        # https://github.com/kachick/dotfiles/commit/deba9834efbef3aae2a61aa6ee2794d1eba6e985#r167396022
        pushFilter: '(-source$|nixpkgs\.tar\.gz$|-vendor)'
