[plugins]
# It is not registered in asdf-vm/plugins and does not appear to be actively maintained. So specify the ref here
# https://github.com/tvon/asdf-podman/tree/974e0fbb6051aaea0a685d8b14587113dfba9173
podman = "https://github.com/tvon/asdf-podman.git#974e0fbb6051aaea0a685d8b14587113dfba9173"
