name: CI - Windows

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-windows.yml'
      - '**.go'
      - 'go.*'
  pull_request:
    paths:
      - '.github/workflows/ci-windows.yml'
      - '**.go'
      - 'go.*'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  setup:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Make sure there are what files before build
        run: Get-ChildItem
      - name: Build winit-* # Avoiding run to measure which step taking minutes
        run: |
          # go build does not automatically create the directory
          New-Item -Force -ItemType "Directory" -Path dist
          # Need -o to keep product in multiple packages
          go build -o dist -v .\..
      - name: Make sure there are what files after build
        run: |
          Get-ChildItem
          Get-ChildItem .\dist
      # Do not write depending winget and WSL2 logcs for now
      # https://github.com/microsoft/winget-cli/issues/3872
      # https://github.com/actions/runner-images/issues/910
      # https://github.com/microsoft/winget-cli/blob/b07d2ebb7d865f95320e2bc708a2d1efb2152c5a/README.md#L14
      - name: Rebel against unacceptable default
        run: |
          .\dist\winit-rebel.exe list
          .\dist\winit-rebel.exe run --all
      # This logics can be finished even if tools are not installed
      - name: Put config files around terminals
        run: .\dist\winit-terminal.exe
