name: CI - Windows

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-windows.yml'
      - '**.go'
      - 'go.*'
  pull_request:
    paths:
      - '.github/workflows/ci-windows.yml'
      - '**.go'
      - 'go.*'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  setup:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Rebel against unacceptable default
        run: |
          go run ./cmd/winit-beep
          go run ./cmd/winit-menu
      # - name: Setup basic tools
      #   run: |
      #     go run ./cmd/winit-terminal
      #     go run ./cmd/winit-wsl
