name: ❄️🐚 🐧
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/devshell-linux.yml'
      - '.github/actions/setup-nix'
      - 'flake.*'
      - 'cmd/**'
      - 'internal/**'
      - '**.nix'
      - 'Taskfile.yml'
      - 'go.*'
  pull_request:
    paths:
      - '.github/workflows/devshell-linux.yml'
      - '.github/actions/setup-nix'
      - 'flake.*'
      - 'cmd/**'
      - 'internal/**'
      - '**.nix'
      - 'Taskfile.yml'
      - 'go.*'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  inspect:
    # Only on Linux is enough to check the flake
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: NixOS/nix-installer-action@main # There are no tagged releases
      - name: Print some dotfiles overviews
        shell: bash -eu -o pipefail {0}
        run: |
          </etc/nix/nix.conf
          ls -alh ~
      - name: Inspect flake outputs
        run: |
          nix flake show
          nix flake show . --json 2>/dev/null | jq '.packages | ."x86_64-linux" | to_entries | map("\(.key) # \(.value.description)")'
      - run: nix flake check --impure
        env:
          # Required to clarify allowing unfree even in check ... :<
          # This does not make problem only here, because this step does not upload any artifacts.
          NIXPKGS_ALLOW_UNFREE: '1'

  tasks:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-slim
          - ubuntu-24.04
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: NixOS/nix-installer-action@main # There are no tagged releases
      - name: Install CI tools
        run: nix profile install .#ci
      - run: task ci-dev

  linters:
    runs-on: ubuntu-24.04 # ubuntu-slim works, but 3x slower
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: NixOS/nix-installer-action@main # There are no tagged releases
      - uses: nix-community/cache-nix-action@v7
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
      - name: Install CI tools
        run: nix profile install .#linters
      - run: dprint check
      - run: typos . .github .vscode
