name: ❄️🐚 🐧
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/devshell-linux.yml'
      - '.github/actions/setup-nix'
      - 'flake.*'
      - 'cmd/**'
      - 'internal/**'
      - '**.nix'
      - 'Taskfile.yml'
      - 'go.*'
  pull_request:
    paths:
      - '.github/workflows/devshell-linux.yml'
      - '.github/actions/setup-nix'
      - 'flake.*'
      - 'cmd/**'
      - 'internal/**'
      - '**.nix'
      - 'Taskfile.yml'
      - 'go.*'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  inspect:
    # Only on Linux is enough to check the flake
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Print some dotfiles overviews
        shell: bash -eu -o pipefail {0}
        run: |
          </etc/nix/nix.conf
          ls -alh ~
      - name: Inspect flake outputs
        run: |
          nix flake show
          nix flake show . --json 2>/dev/null | jq '.packages | ."x86_64-linux" | to_entries | map("\(.key) # \(.value.description)")'
      - run: nix flake check --impure
        env:
          # Required to clarify allowing unfree even in check ... :<
          # This does not make problem only here, because this step does not upload any artifacts.
          NIXPKGS_ALLOW_UNFREE: '1'

  tasks:
    strategy:
      matrix:
        runner: [ubuntu-24.04]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          # Nix shell provides the Go binary. This step is only for enabling standard GitHub Actions caching
          # for Go modules and builds which are not covered by Nix/Cachix in the 'tasks' job.
          go-version-file: 'go.mod'
          cache: true
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Install CI tools
        run: nix profile install .#ci
      - run: task ci-dev
