name: 👕
# Keep lightweght to run on every events.
# See https://github.com/kachick/selfup/blob/c53aad349e3577295a68b1b78ee4cb0eddc4e2b9/README.md#L97-L103 for the motivation
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'

jobs:
  dprint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
        with:
          dprint-version: '0.48.0' # selfup {"extract":"\\d[^']+","replacer":["dprint", "--version"], "nth": 2}
      - name: Setup upterm session
        # This action always use latest CLI
        # https://github.com/owenthereal/action-upterm/blob/4f618b2f5a28013279fff3413093e31d83c9b074/src/index.ts#L20
        uses: owenthereal/action-upterm@5501233b996152ba43e22e8c73c39640f9ae2b3c # v1
        with:
          # Mandatory restrict it
          limit-access-to-users: '${{ github.repository_owner }}'

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.27.3 # selfup {"extract":"\\d\\.\\d+\\.\\d+","replacer":["typos", "--version"], "nth": 2}
        with:
          # https://github.com/crate-ci/typos/issues/779#issuecomment-1635761199
          files: |
            .
            .github
            .vscode

  # Don't use lycheeverse/lychee-action. There is no benefit rather than using the CLI for my use. And considering the targets should be simple with `git ls-files` rather than built-in glob
  link-checker:
    runs-on: ubuntu-24.04
    env:
      CLI_VERSION: '0.18.0' # selfup {"extract":"\\d\\.\\d+\\.\\d+","replacer":["lychee", "--version"], "nth": 2}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          curl -OL 'https://github.com/lycheeverse/lychee/releases/download/lychee-v${{ env.CLI_VERSION }}/lychee-x86_64-unknown-linux-gnu.tar.gz'
          tar zxvf lychee-x86_64-unknown-linux-gnu.tar.gz
          mkdir --parents /home/runner/.lychee/bin
          mv lychee /home/runner/.lychee/bin
          echo '/home/runner/.lychee/bin' >> $GITHUB_PATH
      - name: Run
        env:
          # Not GH_TOKEN for lychee.
          # https://github.com/lycheeverse/lychee/blob/fc006bddc5a63067895799b83cbb9a4cbcabca6a/lychee-bin/src/options.rs#L459-L462
          GITHUB_TOKEN: ${{ github.token }}
        # Don't use glob. It often ignores .gitignore (why?)
        run: |
          git ls-files '*.md' '*.nix' | xargs lychee --
