name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bash env
        run: shopt -s globstar
      - run: shellcheck **/*.bash
  dprint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.1
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bash env
        run: shopt -s globstar
      - name: Install dependencies
        run: go get -u github.com/mvdan/sh/cmd/shfmt
      - run: shfmt -d **/*.bash
