name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  dprint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
        with:
          # Keep same version as used in *.nix
          dprint-version: '0.40.0'

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Keep same version as used in *.nix
      - uses: crate-ci/typos@v1.16.2
        with:
          # https://github.com/crate-ci/typos/issues/779#issuecomment-1635761199
          files: |
            .
            .github
            .vscode
            home/.config
            home/.stack
