name: 👕
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  dprint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
        with:
          dprint-version: '0.45.0' # selfup { "regex": "\\d[^']+", "script": "dprint --version | cut -d ' ' -f 2" }

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.19.0 # selfup { "regex": "\\d\\.\\d+\\.\\d+", "script": "typos --version | cut -d ' ' -f 2" }
        with:
          # https://github.com/crate-ci/typos/issues/779#issuecomment-1635761199
          files: |
            .
            .github
            .vscode
