name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: publicdotfiles
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: print dependency versions
        run: |
          nix-shell --run '
            shellcheck --version
            shfmt --version
            dprint --version
          '
      - name: shellcheck
        run: nix-shell --run 'shopt -s globstar && shellcheck **/*.sh **/*.bash scripts/*.bash .config/.bashrc'
      - name: shfmt
        run: nix-shell --run 'shopt -s globstar && shfmt --diff **/*.sh **/*.bash scripts/*.bash .config/.bashrc'
      - name: dprint
        run: nix-shell --run 'dprint check'
