name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  dprint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
        with:
          dprint-version: '0.34.1'
  shellscript:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      # * ubuntu-latest includes shellcheck, However it is bit old. This ensures to use fixed version.
      # * Standardizing to nix is best, but nix is slow even if installing only tiny binary
      - uses: jdxcode/rtx-action@v1
        with:
          tool_versions: |
            shellcheck 0.9.0
            shfmt 3.6.0
      - name: Logging dependency versions
        run: |
          shellcheck --version
          shfmt --version
      - name: Run linters
        run: |
          shopt -s globstar
          shellcheck ./**/*.bash
          shfmt --diff ./**/*.bash
