name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  dprint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
        with:
          # Keep same version as used in *.nix
          dprint-version: '0.39.1'

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Keep same version as used in *.nix
      - uses: crate-ci/typos@v1.16.1
