name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  dprint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
        with:
          dprint-version: '0.34.1'
  shellscript:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - id: detect_nixpkgs
        name: Detect nixpkgs version
        run: echo "nixpkgs_version=$(nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version' | tr -d '"')" | tee -a $GITHUB_OUTPUT
      - run: nix-build
      - name: Print current versions
        run: |
          nix-shell --run '
            which dprint
            dprint --version
            which shellcheck
            shellcheck --version
            which shfmt
            shfmt --version
            '
      - name: Run linters
        run: |
          ./.githooks/pre-commit
