name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  shellscript:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - run: nix-build
      - name: Print current versions
        run: |
          nix-shell --run '
            which dprint
            dprint --version
            which shellcheck
            shellcheck --version
            which shfmt
            shfmt --version
            '
      - name: Run linters
        run: |
          nix-shell --run './.githooks/pre-commit'
