name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  shellscript:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - id: nixpkgs-version
        name: Detect nixpkgs version
        run: echo "nixpkgs_version=$(nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version' | tr -d '"')" | tee -a $GITHUB_OUTPUT
      # https://github.com/cachix/install-nix-action/issues/56#issuecomment-1240991760
      - name: 'Cache Nix store'
        uses: actions/cache@v3
        id: nix-cache
        with:
          path: /tmp/nixcache
          key: ${{ runner.os }}-nix_${ steps.nixpkgs-version.outputs.nixpkgs_version }
      - name: 'Import Nix store cache'
        if: "steps.nix-cache.outputs.cache-hit == 'true'"
        run: 'nix-store --import < /tmp/nixcache'
      - run: nix-build
      - name: Print current versions
        run: |
          nix-shell --run '
            which dprint
            dprint --version
            which shellcheck
            shellcheck --version
            which shfmt
            shfmt --version
            '
      - name: 'Export Nix store cache'
        if: "steps.nix-cache.outputs.cache-hit != 'true'"
        run: "nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache"
      - name: Run linters
        run: |
          nix-shell --run './.githooks/pre-commit'
