name: 📰❄️
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/notify-nixpkgs-news.yml'
  pull_request:
    paths:
      - '.github/workflows/notify-nixpkgs-news.yml'
  schedule:
    # Every 3rd hour
    # https://crontab.guru/#0_*/3_*_*_*
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '0 */3 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -euxo pipefail {0}'

jobs:
  notify:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'NixOS/nixpkgs'
          ref: nixos-unstable
      - name: Make sure target repository in gh command
        run: 'gh repo set-default --view'
      - name: Notify with issue comment
        run: |
          set +e # Avoid grep error for not found

          # Passing example for test
          git grep --quiet --fixed-string -e 'installShellCompletion' pkgs/by-name/ca/cargo-make/package.nix && \
            gh issue comment '846' --body "🤖(GH-846): https://github.com/NixOS/nixpkgs/tree/nixos-unstable looks like merged https://github.com/NixOS/nixpkgs/commit/3137334d7556e24e3f582681142e505b4d7915a8"

          git grep --quiet --fixed-string -e 'platforms = lib.platforms.linux ++ lib.platforms.darwin' pkgs/by-name/ze/zed-editor/package.nix && \
            gh issue comment '902' --body "🤖(GH-846): https://github.com/NixOS/nixpkgs/tree/nixos-unstable looks like merged https://github.com/NixOS/nixpkgs/commit/67d8538ef6a8b6933de55c09dfcad679a5618868"
