name: 📰❄️
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/notify-nixpkgs-news.yml'
  pull_request:
    paths:
      - '.github/workflows/notify-nixpkgs-news.yml'
  schedule:
    # Every 3rd hour
    # https://crontab.guru/#0_*/3_*_*_*
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '0 */3 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -euxo pipefail {0}'

env:
  # TODO: Make it possible matrix run for the SHA1 list. And takes them from dispatch and merging with fixed list
  # COMMIT_SHA: '67d8538ef6a8b6933de55c09dfcad679a5618868'
  COMMIT_SHA: '3137334d7556e24e3f582681142e505b4d7915a8' # Test
  TRACK_BRANCH: 'nixos-unstable'
  # NOTIFY_ISSUE: '902'
  NOTIFY_ISSUE: '846' # Test

jobs:
  notify:
    runs-on: ubuntu-24.04
    steps:
      # Make it possible to use gh command easy
      # - uses: actions/checkout@v4
      - name: Checkout and fetch minimum commits in nixpkgs
        run: |
          git clone --branch "$TRACK_BRANCH" --single-branch --depth='1' --filter='blob:none' 'https://github.com/NixOS/nixpkgs.git' "$RUNNER_TEMP/nixpkgs"
      - name: Notify with comment
        working-directory: '${{ runner.temp }}/nixpkgs'
        run: |
          git fetch --depth='1' origin "$COMMIT_SHA"
          # TODO: Make sure committer date is correct for shallow-since?
          since="$(git log --date=short --format='%cd' -1 "$COMMIT_SHA"..)"
          git fetch --shallow-since="$since" 'origin' "refs/heads/$TRACK_BRANCH"
      - name: Notify with comment
        working-directory: '${{ runner.temp }}/nixpkgs'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [[ "$(git branch --contains "$COMMIT_SHA" "$TRACK_BRANCH")" == *"nixos-unstable" ]]; then
            gh issue comment "$NOTIFY_ISSUE" --body "🤖(GH-846): https://github.com/NixOS/nixpkgs/tree/$TRACK_BRANCH merged https://github.com/NixOS/nixpkgs/commit/$COMMIT_SHA"
          else
            echo "Not yet merged in the $TRACK_BRANCH"
          fi
