name: 💿 Package NixOS ISO
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
    paths:
      - '.github/workflows/package-iso.yml'
      - 'nixos/hosts/installer/**'
  workflow_dispatch:
  schedule:
    # Every 12:42 JST
    - cron: '42 3 * * *'

permissions:
  contents: read

jobs:
  build:
    # Trigger only on PR with label 'package-iso' OR non-PR events
    if: >-
      github.event_name != 'pull_request' ||
      (github.event_name == 'pull_request' && (
        contains(github.event.pull_request.labels.*.name, 'package-iso') ||
        github.event.action != 'labeled'
      ))
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build NixOS ISO
        run: |
          nix build ".#nixosConfigurations.installer.config.system.build.isoImage" --show-trace
      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v7
        with:
          name: nixos-installer-iso
          path: result/iso/*.iso
