# https://github.com/NixOS/nixos-artwork/blob/35ebbbf01c3119005ed180726c388a01d4d1100c/logo/README.md#L5
name: ❄️📦 🐧
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/package-linux.yml'
      - '.github/actions/setup-nix/**'
      - 'cmd/ci-build/**'
      - 'pkgs/**'
      - 'flake.lock'
      - 'overlays/**'
      - '!**.md'
  pull_request:
    paths:
      - '.github/workflows/package-linux.yml'
      - '.github/actions/setup-nix/**'
      - 'cmd/ci-build/**'
      - 'pkgs/**'
      - 'flake.lock'
      - 'overlays/**'
      - '!**.md'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-26.04
    timeout-minutes: 180
    steps:
      - name: Logging disk space
        run: df -h
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - parallel:
          - name: Build package - archive-home-files
            run: go run ./cmd/ci-build package archive-home-files --arch=x86_64-linux

          - name: Build package - conoha-cli
            run: go run ./cmd/ci-build package conoha-cli --arch=x86_64-linux

          - name: Build package - git-hooks-pre-push
            run: go run ./cmd/ci-build package git-hooks-pre-push --arch=x86_64-linux

          - name: Build package - hcpu_shogi
            run: go run ./cmd/ci-build package hcpu_shogi --arch=x86_64-linux

          - name: Build package - ibm-plex-mono
            run: go run ./cmd/ci-build package ibm-plex-mono --arch=x86_64-linux

          - name: Build package - ibm-plex-sans-jp
            run: go run ./cmd/ci-build package ibm-plex-sans-jp --arch=x86_64-linux

          - name: Build package - ibm-plex-serif-variable
            run: go run ./cmd/ci-build package ibm-plex-serif-variable --arch=x86_64-linux

          - name: Build package - ibus-engine-selector
            run: go run ./cmd/ci-build package ibus-engine-selector --arch=x86_64-linux

          - name: Build package - kanata-tray
            run: go run ./cmd/ci-build package kanata-tray --arch=x86_64-linux

          - name: Build package - lima-full
            run: go run ./cmd/ci-build package lima-full --arch=x86_64-linux

          - name: Build package - mozc
            run: go run ./cmd/ci-build package mozc --arch=x86_64-linux

          - name: Build package - nix-diff
            run: go run ./cmd/ci-build package nix-diff --arch=x86_64-linux

          - name: Build package - reponame
            run: go run ./cmd/ci-build package reponame --arch=x86_64-linux

          - name: Build package - yaneuraou-avx2
            run: go run ./cmd/ci-build package yaneuraou-avx2 --arch=x86_64-linux

          - name: Build package - zed-editor
            run: go run ./cmd/ci-build package zed-editor --arch=x86_64-linux --skip-tests
