name: Push image
on:
  # Do not enable default branch and path in push triggers, use workflow_dispatch for heavy run
  push:
    tags:
      - 'v*'
  schedule:
    # Every 13:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 4 * * *'
  workflow_dispatch:

jobs:
  ghcr:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Wait other jobs
        uses: kachick/wait-other-jobs@v2
        timeout-minutes: 10
        with:
          skip-list: |
            [
              {
                "workflowFile": "release.yml"
              }
            ]
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: home
          tags: latest ${{ github.sha }}
          containerfiles: |
            Containerfile
          oci: true
      - name: Push To ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2.7.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: kachick
          password: ${{ github.token }}
      - name: Log outputs
        run: echo "${{ toJSON(steps.push-to-ghcr.outputs) }}"
