name: Update flake.lock and CI dependencies
on:
  pull_request:
    paths:
      - '.github/workflows/update-flake-lock-and-ci.yml'
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # Every Monday 9:17 JST
    - cron: '17 0 * * 1'
    # Every Thursday 9:17 JST
    - cron: '17 0 * * 4'
  workflow_dispatch:

jobs:
  update-nixpkgs:
    uses: kachick/anylang-template/.github/workflows/reusable-update-nixpkgs-and-versions-in-ci.yml@main
    if: (github.event.sender.login == 'kachick') || (github.event_name != 'pull_request')
    with:
      dry-run: ${{ github.event_name == 'pull_request' }}
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
