name: 🆙❄️
on:
  pull_request:
    paths:
      - '.github/workflows/update-flake-lock-and-ci.yml'
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # Every Monday 9:17 JST
    - cron: '17 0 * * 1'
    # # Every Wednesday 9:17 JST
    # - cron: '17 0 * * 3'
    # # Every Friday 9:17 JST
    # - cron: '17 0 * * 5'
  workflow_dispatch:

jobs:
  flake-inputs:
    permissions:
      contents: write
    if: (github.event_name != 'pull_request') || (!github.event.pull_request.draft)
    uses: kachick/selfup/.github/workflows/reusable-bump-flake-lock-and-selfup.yml@v1.3.0
    with:
      app_id: ${{ vars.APP_ID }}
      dry-run: ${{ github.event_name == 'pull_request' }}
      pr-title: 'Bump flake.lock and related dependencies'
      optional-run: |
        nix run .#bump_gomod -- .
        nix run .#update-completions
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

  local-packages:
    permissions:
      contents: write
    needs: [flake-inputs]
    # Always skips if no conditions
    if: always() && (needs.flake-inputs.result == 'success')
    uses: ./.github/workflows/update-local-packages.yml
    with:
      # Currently hardcoded in selfup's repository: https://github.com/kachick/selfup/blob/5d93696e80f76bee5df93f1c573dd7a1c70c4759/.github/workflows/reusable-bump-flake-lock-and-selfup.yml#L49C18-L49C39
      pr-branch: bot-update-flake-lock
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
