name: 🤖🆙❄️
on:
  pull_request:
    paths:
      - '.github/workflows/update-flake-lock-and-ci.yml'
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # Every Monday 9:17 JST
    - cron: '17 0 * * 1'
    # # Every Wednesday 9:17 JST
    # - cron: '17 0 * * 3'
    # # Every Friday 9:17 JST
    # - cron: '17 0 * * 5'
  workflow_dispatch:

jobs:
  update-nixpkgs:
    if: (github.event_name != 'pull_request') || (!github.event.pull_request.draft)
    uses: kachick/selfup/.github/workflows/reusable-bump-flake-lock-and-selfup.yml@v1.1.9
    with:
      app_id: ${{ vars.APP_ID }}
      dry-run: ${{ github.event_name == 'pull_request' }}
      pr-title: 'Bump flake.lock and related dependencies'
      optional-run: |
        nix run .#bump_gomod -- . pkgs/reponame
        nix run .#bump_gomod -- . pkgs/run_local_hook
        nix run .#bump_gomod -- . pkgs/git-hooks-commit-msg
        nix run .#bump_gomod -- . pkgs/git-hooks-pre-push
        nix run .#update-completions
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
