name: 🤖🆙❄️
on:
  pull_request:
    paths:
      - '.github/workflows/update-flake-lock-and-ci.yml'
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # Every Monday 9:17 JST
    - cron: '17 0 * * 1'
    # Every Thursday 9:17 JST
    - cron: '17 0 * * 4'
  workflow_dispatch:

jobs:
  update-nixpkgs:
    uses: kachick/selfup/.github/workflows/reusable-bump-flake-lock-and-selfup.yml@action-v1
    if: (github.event.sender.login == 'kachick') || (github.event_name != 'pull_request')
    with:
      dry-run: ${{ github.event_name == 'pull_request' }}
      pr-title: 'Bump flake.lock and related dependencies'
      optional-run: |
        nix run .#bump_completions
        git add ./dependencies
        # https://stackoverflow.com/q/34807971
        git update-index -q --really-refresh
        git diff-index --quiet HEAD || git commit -m 'Update dprint completions' ./dependencies/dprint
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
